#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : memkind
Version  : 1.13.0
Release  : 12
URL      : https://github.com/memkind/memkind/archive/v1.13.0/memkind-1.13.0.tar.gz
Source0  : https://github.com/memkind/memkind/archive/v1.13.0/memkind-1.13.0.tar.gz
Summary  : User Extensible Heap Manager
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: memkind-bin = %{version}-%{release}
Requires: memkind-filemap = %{version}-%{release}
Requires: memkind-lib = %{version}-%{release}
Requires: memkind-license = %{version}-%{release}
Requires: memkind-man = %{version}-%{release}
BuildRequires : numactl-dev
BuildRequires : pytest

%description
# **MEMKIND**
[![Build Status](https://github.com/memkind/memkind/workflows/MEMKIND/badge.svg?branch=master)](https://github.com/memkind/memkind/actions)
[![MEMKIND version](https://img.shields.io/github/tag/memkind/memkind.svg)](https://github.com/memkind/memkind/releases/latest)
[![Coverage Status](http://codecov.io/github/memkind/memkind/coverage.svg?branch=master)](http://codecov.io/gh/memkind/memkind?branch=master)
[![Packaging status](https://repology.org/badge/tiny-repos/memkind.svg)](https://repology.org/project/memkind/versions)
[![Language grade: C/C++](https://img.shields.io/lgtm/grade/cpp/g/memkind/memkind.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/memkind/memkind/context:cpp)

%package bin
Summary: bin components for the memkind package.
Group: Binaries
Requires: memkind-license = %{version}-%{release}
Requires: memkind-filemap = %{version}-%{release}

%description bin
bin components for the memkind package.


%package dev
Summary: dev components for the memkind package.
Group: Development
Requires: memkind-lib = %{version}-%{release}
Requires: memkind-bin = %{version}-%{release}
Provides: memkind-devel = %{version}-%{release}
Requires: memkind = %{version}-%{release}

%description dev
dev components for the memkind package.


%package doc
Summary: doc components for the memkind package.
Group: Documentation
Requires: memkind-man = %{version}-%{release}

%description doc
doc components for the memkind package.


%package filemap
Summary: filemap components for the memkind package.
Group: Default

%description filemap
filemap components for the memkind package.


%package lib
Summary: lib components for the memkind package.
Group: Libraries
Requires: memkind-license = %{version}-%{release}
Requires: memkind-filemap = %{version}-%{release}

%description lib
lib components for the memkind package.


%package license
Summary: license components for the memkind package.
Group: Default

%description license
license components for the memkind package.


%package man
Summary: man components for the memkind package.
Group: Default

%description man
man components for the memkind package.


%prep
%setup -q -n memkind-1.13.0
cd %{_builddir}/memkind-1.13.0
pushd ..
cp -a memkind-1.13.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1640285832
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}  || ./build.sh --prefix=/usr --libdir=/usr/lib64

pushd ../buildavx2
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
make  %{?_smp_mflags}  || ./build.sh --prefix=/usr --libdir=/usr/lib64
popd

%install
export SOURCE_DATE_EPOCH=1640285832
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/memkind
cp %{_builddir}/memkind-1.13.0/COPYING %{buildroot}/usr/share/package-licenses/memkind/94e80186052c71e12fee017b5279c8f8b18c450b
cp %{_builddir}/memkind-1.13.0/jemalloc/COPYING %{buildroot}/usr/share/package-licenses/memkind/c797cef3f1b13a960a5119a084fb88529a924fd7
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot}/usr/share/clear/optimized-elf/ %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/memkind-auto-dax-kmem-nodes
/usr/bin/memkind-hbw-nodes
/usr/share/clear/optimized-elf/bin*

%files dev
%defattr(-,root,root,-)
/usr/include/fixed_allocator.h
/usr/include/hbw_allocator.h
/usr/include/hbwmalloc.h
/usr/include/memkind.h
/usr/include/memkind_allocator.h
/usr/include/memkind_deprecated.h
/usr/include/pmem_allocator.h
/usr/lib64/libautohbw.so
/usr/lib64/libmemkind.so
/usr/lib64/libmemtier.so
/usr/lib64/pkgconfig/memkind.pc
/usr/share/man/man3/fixedallocator.3
/usr/share/man/man3/hbwallocator.3
/usr/share/man/man3/hbwmalloc.3
/usr/share/man/man3/memkind.3
/usr/share/man/man3/memkind_arena.3
/usr/share/man/man3/memkind_dax_kmem.3
/usr/share/man/man3/memkind_default.3
/usr/share/man/man3/memkind_fixed.3
/usr/share/man/man3/memkind_hbw.3
/usr/share/man/man3/memkind_hugetlb.3
/usr/share/man/man3/memkind_memtier.3
/usr/share/man/man3/memkind_pmem.3
/usr/share/man/man3/memkindallocator.3
/usr/share/man/man3/pmemallocator.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/memkind/*

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-memkind

%files lib
%defattr(-,root,root,-)
/usr/lib64/libautohbw.so.0
/usr/lib64/libautohbw.so.0.0.0
/usr/lib64/libmemkind.so.0
/usr/lib64/libmemkind.so.0.0.1
/usr/lib64/libmemtier.so.0
/usr/lib64/libmemtier.so.0.0.0
/usr/share/clear/optimized-elf/lib*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/memkind/94e80186052c71e12fee017b5279c8f8b18c450b
/usr/share/package-licenses/memkind/c797cef3f1b13a960a5119a084fb88529a924fd7

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/memkind-auto-dax-kmem-nodes.1
/usr/share/man/man1/memkind-hbw-nodes.1
/usr/share/man/man7/autohbw.7
/usr/share/man/man7/memtier.7
