#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : memkind
Version  : 1.7.0
Release  : 3
URL      : https://github.com/memkind/memkind/archive/v1.7.0.tar.gz
Source0  : https://github.com/memkind/memkind/archive/v1.7.0.tar.gz
Summary  : A general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: memkind-bin
Requires: memkind-lib
Requires: memkind-doc
BuildRequires : numactl-dev

%description
MEMKIND
=======
[![Build Status](https://travis-ci.org/memkind/memkind.svg)](https://travis-ci.org/memkind/memkind)
[![MEMKIND version](https://img.shields.io/github/tag/memkind/memkind.svg)](https://github.com/memkind/memkind/releases/latest)

%package bin
Summary: bin components for the memkind package.
Group: Binaries

%description bin
bin components for the memkind package.


%package dev
Summary: dev components for the memkind package.
Group: Development
Requires: memkind-lib
Requires: memkind-bin
Provides: memkind-devel

%description dev
dev components for the memkind package.


%package doc
Summary: doc components for the memkind package.
Group: Documentation

%description doc
doc components for the memkind package.


%package lib
Summary: lib components for the memkind package.
Group: Libraries

%description lib
lib components for the memkind package.


%prep
%setup -q -n memkind-1.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1528132335
make  %{?_smp_mflags} || ./build.sh --prefix=/usr --libdir=/usr/lib64

%install
export SOURCE_DATE_EPOCH=1528132335
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/memkind-hbw-nodes

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/memkind/internal/heap_manager.h
/usr/include/memkind/internal/memkind_arena.h
/usr/include/memkind/internal/memkind_default.h
/usr/include/memkind/internal/memkind_gbtlb.h
/usr/include/memkind/internal/memkind_hbw.h
/usr/include/memkind/internal/memkind_hugetlb.h
/usr/include/memkind/internal/memkind_interleave.h
/usr/include/memkind/internal/memkind_log.h
/usr/include/memkind/internal/memkind_pmem.h
/usr/include/memkind/internal/memkind_private.h
/usr/include/memkind/internal/memkind_regular.h
/usr/include/memkind/internal/tbb_mem_pool_policy.h
/usr/include/memkind/internal/tbb_wrapper.h
/usr/lib64/libautohbw.so
/usr/lib64/libmemkind.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/memkind/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libautohbw.so.0
/usr/lib64/libautohbw.so.0.0.0
/usr/lib64/libmemkind.so.0
/usr/lib64/libmemkind.so.0.0.1
