#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : memkind
Version  : 1.7.0
Release  : 1
URL      : https://github.com/memkind/memkind/archive/v1.7.0.tar.gz
Source0  : https://github.com/memkind/memkind/archive/v1.7.0.tar.gz
Summary  : A general purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support.
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
BuildRequires : numactl-dev

%description
MEMKIND
=======
[![Build Status](https://travis-ci.org/memkind/memkind.svg)](https://travis-ci.org/memkind/memkind)
[![MEMKIND version](https://img.shields.io/github/tag/memkind/memkind.svg)](https://github.com/memkind/memkind/releases/latest)

%package dev
Summary: dev components for the memkind package.
Group: Development
Provides: memkind-devel

%description dev
dev components for the memkind package.


%prep
%setup -q -n memkind-1.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1527788676
make  %{?_smp_mflags} & ./build.sh

%install
export SOURCE_DATE_EPOCH=1527788676
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/local/bin/memkind-hbw-nodes
/usr/local/lib/libautohbw.so
/usr/local/lib/libautohbw.so.0
/usr/local/lib/libautohbw.so.0.0.0
/usr/local/lib/libmemkind.so
/usr/local/lib/libmemkind.so.0
/usr/local/lib/libmemkind.so.0.0.1
/usr/local/share/doc/memkind/COPYING
/usr/local/share/doc/memkind/README
/usr/local/share/doc/memkind/VERSION
/usr/local/share/man/man3/hbwallocator.3
/usr/local/share/man/man3/hbwmalloc.3
/usr/local/share/man/man3/memkind.3
/usr/local/share/man/man3/memkind_arena.3
/usr/local/share/man/man3/memkind_default.3
/usr/local/share/man/man3/memkind_hbw.3
/usr/local/share/man/man3/memkind_hugetlb.3
/usr/local/share/man/man3/memkind_pmem.3

%files dev
%defattr(-,root,root,-)
/usr/local/include/hbw_allocator.h
/usr/local/include/hbwmalloc.h
/usr/local/include/memkind.h
/usr/local/include/memkind/internal/heap_manager.h
/usr/local/include/memkind/internal/memkind_arena.h
/usr/local/include/memkind/internal/memkind_default.h
/usr/local/include/memkind/internal/memkind_gbtlb.h
/usr/local/include/memkind/internal/memkind_hbw.h
/usr/local/include/memkind/internal/memkind_hugetlb.h
/usr/local/include/memkind/internal/memkind_interleave.h
/usr/local/include/memkind/internal/memkind_log.h
/usr/local/include/memkind/internal/memkind_pmem.h
/usr/local/include/memkind/internal/memkind_private.h
/usr/local/include/memkind/internal/memkind_regular.h
/usr/local/include/memkind/internal/tbb_mem_pool_policy.h
/usr/local/include/memkind/internal/tbb_wrapper.h
/usr/local/include/memkind_deprecated.h
